language: ruby
cache:
  bundler: true
dist: trusty
sudo: false
rvm:
- 2.3.4
before_script:
- bundle exec rake clean
script:
- bundle exec rake
deploy:
  - provider: rubygems
    api_key:
      secure: fW0oDAE1v8l0ksfQwkil7zy29jivBE/y7Vbl1PZ/A/ece35SBiKQvf6r65uOGHqeUMT+Tscwj3qU0lUfaU2aN2zASkIeMr5nMtzgAJE3wzr9j4a8mdbscJVwm1kSiG+B0angENdr8HTPAU4s8dvP4CdP/kB44RIiYMb7JRVJQQ+SqXoMHJdkHEYYCFfCyn1AbWZil22bk0VvzS9DJ/Ehl20ixILWnvPULcPD2sXEmbQ2oBzdM2j4Kty4Kld9bdSjFq9kuJCyvi0K5V6MqxlQ7QZSoZFm82VklwEYdgRKL3Zi1kAbmtahrirDJXmp57wPOQAFSeKbYVdiMgDW71KCx8I23XlIySDMoQkd9RXwWNHZSx29t+HvTfx4ob2imfKPsDX/4z1SGhofwv03My/zbEnK9jrsYSstyosrWwUy07O97INs4NAVRbcqVurrrOOayJLvmIeuaPPWBEV5HYQrYmdB+ao4J+ZJy3PoMnkilbP5bJAvnNkRD8fkgq57llwocWT4hz9ecaZV+ogHcD4HbhnxPlZA7f0wEaEcjdJJduzkx9gOdlFdH5lymAiFPd+rfskc6OGTBs0ai0DD9udOu/qvxBn5lxDwGE1DJseCLtjgUyhKRYuFo+8tifylSMfjsGeRjYXWa0UvTdEe4jKHZPMENBgYOi4fW5vUItjLst4=
    gem: amber
    on:
      tags: true
      repo: Traap/amber
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: lHBZLPv6a7xdtDs/CpcOaBnx/1iicfuxQfK3+I9hvf29/nEgPinfYuGkf5lu+Cwz3Im5yJZCpnLq+lyLkx+Wd/z1PtUEU/j97AekIXtRksHx16Bim1hHW+Xco3lyRRw25GbVsbuGm1GT0wM59kOtUysi8ufnqo5drc6AfN0neryEtnjeK7Rl6PuGeg0761rgYSFP7KesaFutgKf+emfk6HNmxN9yTALJYBAAgCAEbHLV4hyKan64Ob23cAK2ClTHSXN5Mc716Syz23VfLlj2gJzS1TroXNSnipbGmo1w0d4BZxodi5SWzxiv/QgwTfGVfyY220NM+LK5P6w9OCPM4AIbw1vVhkj1t8L8ivfeJu5ABkYWxZEvG97vAD4Eu5skArqJP5BKceyevJhhlv9ti+Hwrm6V7cBVyIVURRT5/8kcC3T7AnIg/Qwg8TMySV1MaPX+8pOBzv+Z2Q2/1lfYVJL/yX37lGr8v5HNkB1w8La0pySxN7OALG43X6xwMMceg523z8YHAqsCwC1La5dLiRCbcQ9gpgUGtSTreWAx/v7iew0L7Fc7mB4juASBruj/AOcw1Gf67nmMTLPX28dte9OA4J3GT1TKBH6ln2MVDnhPoTFFdikx4+g1n7WCD/5azSEax+KT309TOeg3984mHeBhhn2pZ2zA2PVFIGsUTZI=
    file: README.md 
    on:
      tags: true
      branch: master
      repo: Traap/amber
notifications:
  email: false
  slack: allanconsulting:EmHXAakvTUf7qbih0blfDdKs
